[INFO] (2016-11-11 12:32:02,314) Config file successfully read
[INFO] (2016-11-11 12:32:02,338) Connection to database 'TEMPLeidos' successful
[INFO] (2016-11-11 12:32:02,338) Database 'TEMPLeidos' successfully initialized
[INFO] (2016-11-11 12:32:02,339) Starting tokenizer
[INFO] (2016-11-11 12:32:02,339) Editing tokenizer config file in 'bin/tokenizer/config.ini'
[INFO] (2016-11-11 12:32:02,339) Starting tokenizer, output in 'bin/tokenizer/output-1478896322.34'
[ERROR] (2016-11-11 12:32:02,359) An error occured on the tokenizer
[ERROR] (2016-11-11 12:32:02,359) Command 'python bin/tokenizer/tokenizer.py' returned non-zero exit status 1
[INFO] (2016-11-11 12:32:02,359) Tokenizer finished
